env: "local" # local, dev, prod
storage_path: "./storage/url-shortener.db"
http_server:
  address: "localhost:8082"
  timeout: 4s # время на чтение запроса и время на отправку ответа
  idle_timeout: 60s # время жизни соединения с клиентом
  username: admin
  password: admin